spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true

    show-sql: true
   # open-in-view: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8080

topic:
  vehicle:
    name: t.vehicle.create
  track:
    name: t.track.generate